name: Release Pipeline
on:
  push:
    tags:
      - '**'

jobs:
  build:
    env: 
      RUNNER_TOOL_CACHE: /toolcache
    name: Build & Test

    runs-on: linux
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3-beta

      - name: KTLint & Detekt
        run: ./analyze_code.sh -q
      - name: Build & Test
        run: ./gradlew --console=plain clean koverHtmlReport koverHtmlReportRelease releaseJar packageLinuxX64 packageWinX64 packageMacOSX64 assembleRelease
      - name: Create a Release
        uses: akkuman/gitea-release-action@v1
        with:
          files: |-
            **/build/reports/kover/*
            androidApp/build/outputs/apk/release/*.apk
            desktopApp/build/libs/desktopApp-release-*.jar
            desktopApp/build/package/**/release-*.zip
            desktopApp/build/proguard/mapping.txt