name: Release Pipeline
on:
  push:
    tags:
      - '**'

jobs:
  build:
    env: 
      RUNNER_TOOL_CACHE: /toolcache
    name: Build & Test

    runs-on: linux
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3-beta
      - name: echo contains pre
        run: echo ${{ contains(github.ref_name, '_pre') }}
      - name: Create a Release
        uses: akkuman/gitea-release-action@v1
        with:
          prerelease: ${{ contains(github.ref_name, '_pre') }}