[versions]
activity-compose = "1.8.0"
appcompat = "1.6.1"
core-ktx = "1.10.1"
image-loader = "1.2.10"
jsoup = "1.16.1"
koin-android = "3.5.0"
koin-compose = "1.1.0"
kotlinx-coroutines-core = "1.7.3"
kotlinx-serialization-json = "1.6.0"
kotlinx-datetime = "0.4.1"
ktor = "2.3.6"
realm = "1.11.1"
mpfilepicker = "2.1.0"
multiplatform-settings-no-arg = "1.1.0"
mvvm = "0.16.1"
okio = "3.6.0"
slf4j-simple = "2.0.9"
turbine = "0.12.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-android" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-android" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
realm-librarybase = { module = "io.realm.kotlin:library-base", version.ref = "realm" }
mpfilepicker = { module = "com.darkrockstudios:mpfilepicker", version.ref = "mpfilepicker" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings-no-arg" }
mvvm-flow-compose = { module = "dev.icerock.moko:mvvm-flow-compose", version.ref = "mvvm" }
mvvm-compose = { module = "dev.icerock.moko:mvvm-compose", version.ref = "mvvm" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]

[plugins]